name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ingestion script
        run: python ingestion/fetch_breeds.py

      - name: dbt run
        working-directory: dbt
        run: dbt run --profiles-dir .

      - name: dbt test
        working-directory: dbt
        run: dbt test --profiles-dir .
